spring:
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
#  datasource:
#    url: jdbc:mysql://localhost:5440/sa?rewriteBatchedStatements=true
#    username: sa
#    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        jdbc:
          batch_size: 50
#        order_updates: true
#        order_inserts: true
#        generate_statistics: true