
### 문제 조회
GET http://localhost:8080/problems?totalCount=10&unitCodeList=uc1529,uc1536,uc1583&level=MIDDLE&problemType=ALL
Content-Type: application/json

### 학습지 생성
POST http://localhost:8080/piece?userId=2
Content-Type: application/json

{
  "problemIds": [117,118,119,147,148,149,171,272,273],
  "name": "구몬1"
}

### 학습지 출제
POST http://localhost:8080/piece/2
Content-Type: application/json

{
  "studentIds": [1,3,4]
}

### 학습지 문제 조회
GET http://localhost:8080/piece/problems/2?userId=1
Content-Type: application/json


### 문제 채점
PUT http://localhost:8080/piece/problems/2?userId=3
Content-Type: application/json

[
  {
    "problemId": 117,
    "answer": 2
  },
  {
    "problemId": 118,
    "answer": 2
  },
  {
    "problemId": 119,
    "answer": 2
  },
  {
    "problemId": 147,
    "answer": 1
  },
  {
    "problemId": 148,
    "answer": 3
  }

]

### 학습지 통계
GET http://localhost:8080/piece/analyze/2
Content-Type: application/json