
### 문제 조회
GET http://localhost:8080/problems?totalCount=10&unitCodeList=uc1529,uc1536,uc1583,uc1572&level=MIDDLE&problemType=ALL
Content-Type: application/json

### 학습지 생성
POST http://localhost:8080/piece
Content-Type: application/json

{
  "userId": 1,
  "problemIds": [60,61,62,63,65,272,273,274,117],
  "name": "선형대수학"
}

### 학습지 출제
POST http://localhost:8080/piece/6
Content-Type: application/json

{
  "studentIds": [3,4]
}


### 학습지 문제 조회
GET http://localhost:8080/piece/6/problems
Content-Type: application/json


### 문제 채점
PUT http://localhost:8080/piece/6/problems
Content-Type: application/json

{
  "userId": 3,
  "marks": [
      {
        "problemId": 60,
        "answer": 2
      },
      {
        "problemId": 61,
        "answer": 1
      },
      {
        "problemId": 62,
        "answer": 2
      },
      {
        "problemId": 63,
        "answer": 1
      },
      {
        "problemId": 65,
        "answer": 5
      }

    ]
}


### 학습지 통계
GET http://localhost:8080/piece/6/analyze
Content-Type: application/json